services:
    kolemp_timecop.request_based_time_generator:
        class: Kolemp\TimecopBundle\Service\RequestBasedTimeGenerator
        arguments:
            - "%kolemp_timecop.enabled%"
            - "%kolemp_timecop.queryParameter%"
            - "%kolemp_timecop.cookie%"
            - "@event_dispatcher"
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 255 }
          - { name: kernel.event_listener, event: kernel.response, method: onResponse }
