services:
    kolemp_timecop.request_based_time_generator:
        class: Kolemp\TimecopBundle\Service\RequestBasedTimeGenerator
        arguments: ["%kolemp_timecop.enabled%"]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 255 }
